version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    volumes:
      - ./scripts/init-db.cql:/init-db.cql
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Starting Cassandra"
        /docker-entrypoint.sh cassandra -f &
        CASS_PID=$!
        echo "Cassandra started with PID $$CASS_PID"
        echo "Waiting for Cassandra to start"
        while ! cqlsh -e 'describe cluster' >/dev/null 2>&1; do sleep 1; done
        echo "Cassandra started, executing script"
        cqlsh -f /init-db.cql
        echo "Script executed, waiting for Cassandra to exit"
        wait $$CASS_PID

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
